---
title: "wgcna"
author: "Marusa Koderman"
date: '2023-08-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r helpers}
source('code/functions.R')
```

```{r inputs}

organs <- c('blood', 'muscle', 'spleen')

# metadata files
all_samples_info <- read.xlsx("data/metadata/all_samples_info.xlsx")
all_samples_info$wpi <- paste(all_samples_info$wpi, 'wpi')
all_samples_info$wpi <- gsub("term wpi", 'terminal', all_samples_info$wpi) %>%
  factor(., levels = c('4 wpi', '8 wpi', '12 wpi', '14 wpi', '16 wpi', '18 wpi', '20 wpi','terminal')) 

all_samples_info <- all_samples_info %>% mutate(stage = case_when(wpi %in% c('4 wpi', '8 wpi') ~ 'early', 
                                                                  wpi %in% c('12 wpi', '14 wpi', '16 wpi') ~ 'presymptomatic', 
                                                                  TRUE ~ 'symptomatic'))

all_samples_info$stage <- factor(all_samples_info$stage, levels = c('early', 'presymptomatic', 'symptomatic'))


all_samples_info_split <- all_samples_info %>% group_by(Region) %>% 
  group_split() %>%
  setNames(organs) %>%
  lapply(., function(x){
    x <- x %>% as.data.frame()
    rownames(x) <- x$SampleID
    x
    })

# get feature counts 

Fcounts_main_dir <- 'data/FeatureCounts'

all_FC_counts_list <- mapply(organ = c('blood', 'muscle_batch1', 'spleen'),
                             meta = all_samples_info_split,
                             FUN= get_feature_counts,
                             MoreArgs= list(counts_dir = Fcounts_main_dir,
                                            file_prefix = '', 
                             overwrite = FALSE),
                             SIMPLIFY = FALSE) %>%
  setNames(organs)


# get stage deseq2 results for muscle
muscle_deseq2_stage_res <- list.files('output/mouse_pca_and_deseq2', pattern ='.*muscle_deseq2_results.nice.rds', full.names = TRUE) %>%
  .[grepl('early|symptomatic|presymptomatic', .)] %>%
  lapply(.,FUN = readRDS)


# mouse feature data
mouse_feature_meta <- get_feature_data(rownames(all_FC_counts_list[[1]]), 
                                       symbols = 'mgi_symbol', 
                                       mart_dataset = 'mmusculus_gene_ensembl', 
                                       species= 'mouse', 
                                       out_dir = 'data/metadata', 
                                       overwrite = FALSE)
```

```{r outputs}
out_dir <- 'output/wgcna'
# module gene table
module_gene_table_f <- file.path(out_dir, 'all_organs_module_genes.xlsx')

# file with module membershih and per stage deseq2 p-values for darkgreen and orange module
orange_darkgreen_MM_GS_f <- file.path(out_dir, 'orange_darkgreen_MM_GS.csv')

# files for gephi

orange_gephi_nodelist = file.path(out_dir, 'orange_module_gephi_nodelist.csv')
darkgreen_gephi_nodelist = file.path(out_dir, 'darkgreen_module_gephi_nodelist.csv')

orange_gephi_edgelist = file.path(out_dir, 'orange_module_gephi_edgelist.csv')
darkgreen_gephi_edgelist = file.path(out_dir, 'darkgreen_module_gephi_edgelist.csv')

```


```{r get_wgcna_inputs}
wgcna_inputs <- mapply(counts = all_FC_counts_list,
                       sample_info = all_samples_info_split, 
                       file.prefix = c('blood', 'muscle_bacth1', 'spleen'), 
                       FUN = get_input_for_wgcna, 
                       MoreArgs=list(
                         out_dir = out_dir, 
                         overwrite = FALSE), 
                       SIMPLIFY = FALSE) %>%
  setNames(organs)
```


```{r wgcna_power_term_selection}
power <- c(c(1:10), seq(from = 12, to = 50, by = 2))

all_sfts <- mapply(wgcna_input = wgcna_inputs,
                   file.prefix = c('blood', 'muscle_bacth1', 'spleen'), 
                   FUN = pick_soft_threshold, 
                   MoreArgs = list(power_vec = power, 
                                   out_dir = out_dir), 
                   SIMPLIFY = FALSE)
                  
# visualization to pick power
pick_power_plots <- lapply(all_sfts, FUN = make_plot_for_power_selection)

# select soft threshold
soft_thr <- 4
```

```{r get_modules}
#calculate adjacency, TOM and identify modules; this gives initial modules, before merging of similar modules
all_organs_modules <-  mapply(norm.counts = wgcna_inputs,
                   file.prefix = c('blood', 'muscle_bacth1', 'spleen'), 
                   FUN =adj_tom_cluster, 
                   MoreArgs = list(thr = soft_thr, 
                                   out_dir = out_dir), 
                   SIMPLIFY = FALSE)

# merge similar modules (if there are more than n modules, merge modules whose expression profiles are very similar)

all_organs_final_modules_and_MEs <- mapply(norm.counts = wgcna_inputs,
                  colors = all_organs_modules, 
                   file.prefix = c('blood', 'muscle_bacth1', 'spleen'), 
                   FUN = merge_similar_modules, 
                   MoreArgs = list(n = 30, 
                                   out_dir = out_dir, 
                                   overwrite = FALSE), 
                   SIMPLIFY = FALSE)

# make a nice table with all module genes (export to excel)
module_genes_tbl <- mapply(all_organs_final_modules_and_MEs, 
                           org = c('blood', 'muscle', 'spleen') , 
                           FUN=function(x, org){
                             data.frame(module = x$moduleColors, 
                                        ensembl_gene_id = names(x$moduleColors), 
                                        organ =org) %>% 
                               as_tibble() %>%
                               merge(., mouse_feature_meta, by = 'ensembl_gene_id', all.x = TRUE, all.y = FALSE) %>%
                               dplyr::select(ensembl_gene_id, gene_symbol, module, organ) %>%
                               arrange(module)
                           }, SIMPLIFY = FALSE)


```

```{r merge_MEs_w_meta}

meta_w_MEs <- mapply(modules = all_organs_final_modules_and_MEs, 
                     meta = all_samples_info_split, 
                     FUN = function(modules,meta){
                       MEs <- modules$moduleMEs
                       merge_MEs_and_meta(MEs = MEs, meta = meta)
                     }, SIMPLIFY = FALSE)

```

```{r get_ME_signif}
all_ME_signif <- lapply(meta_w_MEs, FUN = all_modules_ME_signif)
```

```{r get_ME_signif_heats}

# get heatmaps that show significant modules in each organ (Supplementary figure 2)
ME_signif_heatmaps_no_leg <- lapply(all_ME_signif, FUN = make_ME_signif_heatmap, legend = 'none')
ME_signif_heatmaps_leg <- lapply(all_ME_signif, FUN = make_ME_signif_heatmap, legend = 'inplot')

```


```{r get_hubs}
# get module membership for muscle darkgreen and orange module
muscle_MMs = get_moduleMembership(module_df = module_genes_tbl$muscle,
                                  MEs_ls = all_organs_final_modules_and_MEs$muscle,
                                  norm.counts = wgcna_inputs$muscle) %>%
  filter(module %in% c('orange', 'darkgreen'))

```

```{r run_stage_DESEQ2}

muscle_info_stage_split <- all_samples_info %>%
  filter(Region == 'muscle') %>%
  mutate(Condition = paste(Treatment, stage, sep = '_'))

rownames(muscle_info_stage_split) = muscle_info_stage_split$SampleID

  muscle_stage_dds <- DESeqDataSetFromMatrix(countData = all_FC_counts_list$muscle,
                                             colData = muscle_info_stage_split,
                                             design = ~Condition)
  # keep genes that were used for wgcna
  # dds_keep <- rowSums(counts(muscle_stage_dds)) >= 10
  muscle_stage_dds <- muscle_stage_dds[colnames(wgcna_inputs$muscle), ]

  # get results

  muscle_stage_dds <- DESeq(muscle_stage_dds)
  m_early_deseq_res = results(muscle_stage_dds, contrast = c('Condition', 'RML6_early', 'NBH_early')) 
  
  m_pre_deseq_res = results(muscle_stage_dds, contrast = c('Condition', "RML6_presymptomatic", "NBH_presymptomatic")) 

  m_sym_deseq_res = results(muscle_stage_dds, contrast = c('Condition', "RML6_symptomatic","NBH_symptomatic")) 


  # make results nicer
  muscle_stage_deseq_nice_res = mapply(res = list(m_early_deseq_res, 
                                                  m_pre_deseq_res,
                                                  m_sym_deseq_res), 
         st = c('early', 'presymptomatic', 'symptomatic'), 
        FUN = function(res, st){
            
    res %>%
    as.data.frame() %>%
    rownames_to_column('ensembl_gene_id') %>%
    dplyr::select(ensembl_gene_id, pvalue, log2FoldChange) %>%
    mutate(stage = st) %>%
    filter(ensembl_gene_id %in% muscle_MMs$ensembl_gene_id)
    
 }, SIMPLIFY = FALSE) %>%
    setNames(c('early', 'presymptomatic', 'symptomatic'))
  
```

```{r get_combined_deseq_score}

muscle_deseq2_sum = metapod::combineParallelPValues(list(muscle_stage_deseq_nice_res$early$pvalue, 
                      muscle_stage_deseq_nice_res$presymptomatic$pvalue, 
                      muscle_stage_deseq_nice_res$symptomatic$pvalue), 
                      method = "stouffer") 

muscle_deseq2_sum_df = data.frame(deseq2_sum.pval = muscle_deseq2_sum$p.value, 
                                  ensembl_gene_id = muscle_stage_deseq_nice_res$early$ensembl_gene_id)

```


```{r merge_MM_and_sum_deseq}
muscle_MM_sum_deseq_merged = merge(muscle_MMs, muscle_deseq2_sum_df, by ='ensembl_gene_id')

# make scatterplots
orange_MM_deseq2_pval_plot = make_MM_deseq2_corr_plot(muscle_MM_sum_deseq_merged %>% filter(module == 'orange'))
darkgreen_MM_deseq2_pval_plot = make_MM_deseq2_corr_plot(muscle_MM_sum_deseq_merged %>% filter(module == 'darkgreen'))                         
```


```{r export_plots}
# module significance heatmaps

# save all plots without legends as svg
ggsave(file.path(out_dir,
                 "muscle_b1_ME_signif_heatmap.svg"), 
       ME_signif_heatmaps_no_leg$muscle, width = 2.3, height = 6.5)

ggsave(file.path(out_dir,
                 "blood_ME_signif_heatmap.svg"), 
       ME_signif_heatmaps_no_leg$blood, width = 2.3, height = 4.7)

ggsave(file.path(out_dir,
                 "spleen_ME_signif_heatmap.svg"), 
       ME_signif_heatmaps_no_leg$spleen, width = 2.3, height = 3)




# save all legends as svg
all_legends <- lapply(ME_signif_heatmaps_leg, FUN = ggpubr::get_legend)
mapply(l = all_legends, f_prefix = c('blood', 'muscle_bacth1', 'spleen'), 
       FUN = function(l, f_prefix){
         ggsave(file.path(out_dir, paste0(f_prefix, '_ME_signif_heat_legend.svg')), 
                l, width = 1, height = 3)
       }, SIMPLIFY = FALSE)


# MM and GS correlation plots
ggsave(file.path(out_dir, "orange_MM_GS_corr_plot.svg"), orange_MM_deseq2_pval_plot, width = 2.5, height = 2)
ggsave(file.path(out_dir, "darkgreen_MS_GS_corr_plot.svg"), darkgreen_MM_deseq2_pval_plot, width = 2.5, height = 2)



```


```{r get_gephi_files}

orange_gephi = get_files_for_gephi(wgcna_inputs$muscle,
                                   thr = 4,
                                   genes_df = muscle_MM_sum_deseq_merged,
                                   module_name = 'orange',
                                   nodelist_f = orange_gephi_nodelist,
                                   edgelist_f = orange_gephi_edgelist,
                                   overwrite = TRUE)


darkgreen_gephi = get_files_for_gephi(wgcna_inputs$muscle,
                                      thr = 4,
                                      genes_df = muscle_MM_sum_deseq_merged,
                                      module_name = 'darkgreen',
                                      nodelist_f = darkgreen_gephi_nodelist,
                                      edgelist_f = darkgreen_gephi_edgelist,
                                      overwrite = TRUE)

```


```{r export_files}

openxlsx::write.xlsx(module_genes_tbl, module_gene_table_f)
write.csv(muscle_MM_sum_deseq_merged, orange_darkgreen_MM_GS_f, row.names = FALSE, quote = FALSE)



```












